### ISSUE TITLE
how to use the plugin

### ISSUE THREAD

**Issue by Devric** [benjie/db-migrate-plugin-babel#3]
Hi 
I'm having trouble using ES6, 'import' is unexpected token

I thought db-migrate will automatically pick up the plugin right?

here is my package.json

```
{
  "name": "dbmigrate",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "babel-register": "^6.26.0",
    "db-migrate": "^0.11.1",
    "db-migrate-mongodb": "^1.4.0",
    "db-migrate-plugin-babel": "benjie/db-migrate-plugin-babel",
    "mongoose": "^5.2.4"
  }
}
```

and this is in one of my migration file

```
import mongoose from 'mongoose'
```

i just call 

yarn db-migrate

**Comment by benjie** [comment]
You need to install `@babel/register` too

**Comment by benjie** [comment]
My bad; you have that. Why haven’t you installed from npm? Not sure if that makes a difference 🤷‍♂️

**Comment by benjie** [comment]
Maybe your babelrc isn’t sufficient; what happens if you “yarn babel migration.js”?

**Comment by Devric** [comment]
yarn and npm wont make a difference, you mean i should try programable api to call db-migration?

and i need babelrc for configuration as well?

how do i debug if your plugin has been loaded correctly.
there isnt much documentation on db-migrate plugins

**Comment by benjie** [comment]
Try and compile your migration javascript file with babel (ignoring db-migrate and this plugin). At the moment I suspect that your babel is not configured (via `.babelrc`) to interpret modules. You probably want to use `babel-preset-env`.

**Comment by artemjackson** [comment]
@Devric you may want to retry to use the plugin
